### ISSUE TITLE
Cannot decompress

### ISSUE THREAD

**Issue by yuansliu** [kowallus/PgTools#1]
Hi Tomasz,

I clone the latest source code (access data Oct 10, 2019). 
![image](https://user-images.githubusercontent.com/7776655/66534678-b3f4d480-eb62-11e9-8973-aaaf38d909c1.png)

Run the following cmd:
*./PgRC -i test.fastq test.pgrc*

All output as following:

Filtered 704 (including 704 containing N) reads (out of 500000) in 750 msec.
HQ reads count: 499296
Found 1386 duplicates.
Overlapping done in 4620 msec
Found 13424 both-side overlapped reads in 4630 msec
HQ reads count: 13424
Found 1386 duplicates.
Overlapping done in 40 msec
LQ reads count: 485872
N reads count: 704
Target pseudogenome length: 337996
readsAlignmentSeedLength (minCharsPerMismatch, matchingMode): 38 (6, c)
Feeding pseudogenome sequence... 
copMEM PARAMETERS: l = 38; K = 28; HASH_SIZE = 16777216; k1 = 5; k2 = 2
Matched 30264 reads (456312 left; 15428 better-matches). False matches reported: 5953141.
Feeding rc of pseudogenome sequence... 
copMEM PARAMETERS: l = 38; K = 28; HASH_SIZE = 16777216; k1 = 5; k2 = 2
Matched 33900 reads (452676 left; 22536 better-matches). False matches reported: 7414429.
LQ reads count: 452031
Found 0 duplicates.
Overlapping done in 5910 msec
N reads count: 645
Found 0 duplicates.
Overlapping done in 0 msec
Source pseudogenome length: 337996
copMEM PARAMETERS: l = 50; K = 36; HASH_SIZE = 16777216; k1 = 5; k2 = 3
Destination pseudogenome length: 41350429
Final size of Pg: 41174938 (removed: 178332 (0.4%); 17773 chars in overlapped dest symbol)
Destination pseudogenome length: 64745
Final size of Pg: 64440 (removed: 310 (0.4%); 0 chars in overlapped dest symbol)
Final size of Pg: 172696 (removed: 167060 (49.4%); 61718 chars in overlapped dest symbol)

Created PgRC of size 10153394 bytes in 59.96 s.

Then, I try to decompress it using the following cmd:
*./PgRC -i test.pgrc -d decresult*

BUT, the output is: 

_Cannot read pseudogenome properties (decresult/good does not open)._

**Comment by kowallus** [comment]
The correct command for decompression would be:
./PgRC -d test.pgrc 
Sorry, the usage description is confusing. Thanks for info I will make an update.

**Comment by yuansliu** [comment]
TKS
