### ISSUE TITLE
Unsupported variable length reads.

### ISSUE THREAD

**Issue by i-xiaohu** [kowallus/PgTools#2]
I input a fixed-length reads FASTQ file
Use the cmd: "_PgRC -i ../data1.fq -o data1.pgrc_"
But PgRC output: "_Unsupported variable length reads._"

**Comment by kowallus** [comment]
Could you please make data1.fq available?

**Comment by i-xiaohu** [comment]
Ok,  to check the report, I only selected two reads of length 150 to test PgRC. 
Besides, I skimed the source code and added the line 
`fprintf(stderr, "readLength = %d, minReadLength = %d\n", readLength, properties->minReadLength);`
to check the "properties"  in Function 
`void PackedConstantLengthReadsSet::addRead(const char* read, uint_read_len_max readLength)`

Then PgRC output:
_readLength = 150, minReadLength = 0
Unsupported variable length reads._

**The data1.fq:**
@ecoli_2727933_2728382_0/1
TGGTCGTCCACGCCGTAAACGATGTCGACTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCGAATGAAATGACGGGGGCCCGCACAAGCGGTGAAG
+
555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
@ecoli_2847775_2848188_1/1
GCGGATTGCGCAGGCGCAACTGAGCATTGACGGCATGATTGATGGCAAGGTCAACGTCCGCGATCGCGAACAGGTTCTGGAACACTATCTCGAAAAAATCGCTGGCGTTTACGACAGCTTATACACCGCAATTGAAAACAATGTGCCGGT
+
555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555

**Comment by kowallus** [comment]
Have you tried changing extension to fastq?

**Comment by i-xiaohu** [comment]
Thanks for your response, problem solved!
P.S. I do suggest you add some illustrations in _README_.  Actually the extension "fq" is very common.

**Comment by kowallus** [comment]
Thanks for the feedback. I hope I will improve format recognition for the next release.
