### ISSUE TITLE
compile error in version 1.2

### ISSUE THREAD

**Issue by ttan6729** [kowallus/PgTools#3]
After cmake (version 3.4), make PgRC return
`[ 78%] Building CXX object CMakeFiles/PgRC.dir/matching/ReadsMatchers.cpp.o
/projects/NGSData/RNACompression/PgRCBranch/PgRC/matching/ReadsMatchers.cpp: In member function ‘virtual void PgTools::CopMEMRe                     adsApproxMatcher::executeMatching(bool)’:
/projects/NGSData/RNACompression/PgRCBranch/PgRC/matching/ReadsMatchers.cpp:419:99: error: expected ‘)’ before ‘[’ token
                                 reduction(+:falseMatchCount) reduction(+:matchedCountPerMismatches[0:NOT_MATCHED_COUNT+1])
                                                                                                   ^
/projects/NGSData/RNACompression/PgRCBranch/PgRC/matching/ReadsMatchers.cpp:419:123: error: ‘PgTools::DefaultReadsMatcher::matc                     hedReadsCount’ is not a variable in clause ‘reduction’
/projects/NGSData/RNACompression/PgRCBranch/PgRC/matching/ReadsMatchers.cpp:419:123: error: ‘PgTools::DefaultReadsMatcher::bett                     erMatchCount’ is not a variable in clause ‘reduction’
/projects/NGSData/RNACompression/PgRCBranch/PgRC/matching/ReadsMatchers.cpp:419:123: error: ‘PgTools::DefaultReadsMatcher::fals                     eMatchCount’ is not a variable in clause ‘reduction’
/projects/NGSData/RNACompression/PgRCBranch/PgRC/matching/ReadsMatchers.cpp:419:123: error: ‘PgTools::AbstractReadsApproxMatche                     r::matchedCountPerMismatches’ is not a variable in clause ‘reduction’
`

**Comment by kowallus** [comment]
I think that your compiler lacks OpenMP library. Sorry, but CMakeList is not prepared to handle OpenMP package properly.
Try replacing:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
with:
FIND_PACKAGE( OpenMP REQUIRED)
message(STATUS "OpenMP FOUND")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")

Could you write what is your OS and compiler?

**Comment by ttan6729** [comment]
My previous OS and compiler is linux, g++ 3.8.5. 

Yes, that's true, the reason for error is that I use compiler that lacks OpenMP lib. After changing compiler to g++ 6.3.1, the program works fine. Thanks a lot for help.

**Comment by kowallus** [comment]
Great! Thanks for the feedback.
