### ISSUE TITLE
segmentation fault in parallel version

### ISSUE THREAD

**Issue by ttan6729** [kowallus/PgTools#4]
The new parallel version return segmentation fault for http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR116/SRR116699/SRR116699.fastq.gz, it returns
"Filtered 143 (including 143 containing N) reads (out of 320272) in 195 msec.
HQ reads count: 320129
Found 136787 duplicates (...23 msec)
Segmentation fault".

The previous version works fine, sees the error is in parallel computing for searching overlapping.

**Comment by kowallus** [comment]
Thank you. I reproduced the error and I will look into it soon.

**Comment by kowallus** [comment]
Please check out the latest changes and let me know.
I hope that now everything will be fine.
