### ISSUE TITLE
Base Count is coming different from original file for decompressed file of PgRC

### ISSUE THREAD

**Issue by Abby3017** [kowallus/PgTools#6]
Hey,

I am running latest version of PgRC for compressing the fastq file. I ran following command:

1. To compress the file - ./PgRC -o -c 2 -t 24 -i in1.fastq in2.fastq comp.pgrc
2. To decompress the file - ./PgRC -t 24 -d hg001_1.pgrc
3. DataSet - HG001 (gold dataset) can be downloaded from below command from google cloud 
   
> gsutil -m cp \
>   "gs://brain-genomics-public/research/sequencing/fastq/novaseq/wgs_pcr_free/30x/HG001.novaseq.pcr-free.30x.R1.fastq.gz" \
>   "gs://brain-genomics-public/research/sequencing/fastq/novaseq/wgs_pcr_free/30x/HG001.novaseq.pcr-free.30x.R2.fastq.gz" \
>   .
[Google download link](https://console.cloud.google.com/storage/browser/brain-genomics-public/research/sequencing/fastq/novaseq/wgs_pcr_free/30x?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

The Base Sequence count present before compression is:

HG001 R1 (Original) | HG001 R2 (Original)
-- | --
A: 16033893975 | A: 16139558770
C: 11226235853 | C: 11222480122
T: 15949617335 | T: 15817200949
G: 11320992754 | G: 11352215013
N: 1813974 | N: 1099037

After compressing and decompressing the file, we got following count:

HG001 R1| HG001 R2
-- | --
A: 16037782532 | A: 16142607048
C: 11222597210 | C: 11218877813
T: 15953541920 | T: 15821850191
G: 11316818263 | G: 11348119830
N: 1813966 | N: 1099009

Total count is same but you can see the discrepancy between the base count.
Compressed size of total dataset is 3.4 Gb and decompressed size is 52 Gb each for pair end.

It will be great, if you can take a look into this issue and if you need any other info please let me know.

**Comment by kowallus** [comment]
Thank you. I will see into it in few days.

**Comment by kowallus** [comment]
The fix is uploaded. Please check.

**Comment by Abby3017** [comment]
Hey, 
I ran the updated code on the given dataset. The compression is working fine. Its generating the compress file of size 2.3 Gb with reordering allowed. But when I try to decompress, it generate two files of size 28Gb and 0 byte for pair end, earlier I was getting 52 Gb each. I ran decompression twice and got the same result. Can you verify from your end and look into this ?

**Comment by kowallus** [comment]
Are you sure you didn't run out of disk space?

**Comment by kowallus** [comment]
Works fine at my end. If it is not a problem with disk space then maybe you could make the archive available for me to test?

**Comment by Abby3017** [comment]
Hey,
Last Issue was due to disk space shortage. Thanks for pointing that out. If program can give relevant error output instead of showing completion success message, it would be helpful.
I ran the experiment and still count is not showing accurate. Here is the updated count I got after running with new code.

R1 | R2
-- | --
A: 16040744279 | A: 16145751638
C: 11219645658 | C: 11215818719
T: 15956576790 | T: 15824585669
G: 11313773190 | G: 11345298828
N: 1813974 | N: 1099037


Thanks again for looking into this.

**Comment by kowallus** [comment]
Preliminary verification shows no errors, however, I will do a second check tomorrow. It would be helpful if you could make the archive available for me to test.

**Comment by kowallus** [comment]
Everything checks out fine for me (also with an almost twice as large dataset). Maybe you haven't succeeded with updating the tool? Please check the release date:
`PgRC -?`
Otherwise, I would need the archive for further investigation.

**Comment by Abby3017** [comment]
I cloned the master branch which have your last commit. For archive, should I provide you compress file or you need both compressed and decompressed file ?

**Comment by kowallus** [comment]
Compressed would be sufficient. Just to make sure, what is your release date when you run the tool with -? option?

**Comment by Abby3017** [comment]
This is the release date I got. 
`PgRC 1.2: Copyright (c) 2021 Tomasz Kowalski, Szymon Grabowski: 2021-05-03`
Here is the [link](https://indianinstituteofscience-my.sharepoint.com/:u:/g/personal/abhinavk_iisc_ac_in/EVCEsnjS3RBHir2Vb3POcaABTWVTPlUWVuL5NBIbK1pBFA?e=pLV3gn) for the archive.

**Comment by kowallus** [comment]
I have tested compression and decompression three times on two different machines and everything checks out fine every time.
In the case of the archive you provided in fact there are errors in decompressed reads however I cannot point out the cause. When I compress using 24 threads I get an archive with the about size as yours but without any discrepancies.
I don't know how to approach this problem. Could you provide more details about your environment (compiler, processor, OS, etc.)?
P.S. I would also appreciate it if you could perform a memory test on your machine, and test PgRC and this dataset on another machine to exclude hardware errors on your side.

**Comment by Abby3017** [comment]
System information:

- CPU : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
- Cores: 32
- RAM: 512 Gb
- LINUX: 3.10.0-862.3.2.el7.x86_64
- OS: CentOS Linux 7 (Core)
- gcc-7.5

I will run the PgRC on other machine and will let you know the result.

**Comment by kowallus** [comment]
Can you send me the archive without reordering also? It should make it easier to locate the compression stage where the error might occur.
Have you checked PgRC on another machine or done a memory test?

**Comment by Abby3017** [comment]
I ran PgRC on another machine with given configuration:

- Intel(R) Xeon(R) Gold 6226R CPU @ 2.90GHz
- Cores: 64
- RAM: 256 Gb
- Linux:  3.10.0-957.el7.x86_64
- OS: CentOS Linux 7 (Core)
- gcc-7.5

Still count is not coming correct on this system. For memory test are you talking about `memtester` or it is other test (can you explain more) ?
I will share that archive too.

**Comment by kowallus** [comment]
If the same errors occur on two different machines I think that memory test is not necessary. Maybe, the reason of error is some issue associated with the gcc version since I have always been using newer versions. I will try looking into it. 
Do similar counting discrepancies occur also on smaller fastq datasets?

**Comment by Abby3017** [comment]
I ran another experiment with 7.2 Gb pair end files. Discrepancies were there. Can you tell me your gcc and cmake version, so that I can try building PgRC with that and then run my experiments ?

**Comment by kowallus** [comment]
Thanks for info. On one machine I have gcc 9.3.0 and cmake version 3.16.3.

**Comment by kowallus** [comment]
I partly recreated your environment (centos + gcc 7.5) and found an error (undefined behavior bug). I hope that now PgRC will work flawlessly ;). I am waiting for confirmation from you.

**Comment by Abby3017** [comment]
It's working correctly. Thanks for looking into this issue and resolving it.

**Comment by kowallus** [comment]
Thank you
