### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Nirmal2310** [kowallus/PgTools#7]
Hey,

I am trying to build PgRC on servers I am getting build errors.
I am using cmake version 3.19.7 and gcc version 9.3.0.
![issue](https://user-images.githubusercontent.com/62856422/140694752-e64b7ad4-7a05-4115-b8a5-12a808ec9bd4.JPG)
Thank you for looking into this matter and please let me know if you need any additional information.

**Comment by kowallus** [comment]
I would recommend cleaning up all gcc installations and fresh install.
Folders like /usr/include/c++/4.8.2 indicate that your 9.3.0 gcc uses includes (e.g. header files) from the version 4.8.2.
I suppose you have also /usr/include/c++/9 folder, but it has a lower priority.

**Comment by Nirmal2310** [comment]
Thank you for responding so quickly, I am setting this tool on a cluster in which the gcc 9.3.0 can be avail only using module load command. So, I can't upgrade the system gcc version as I have no root access. Can you suggest some alternate way to deal with this problem.
Thank you so much.

**Comment by kowallus** [comment]
Maybe you can compile PgRC on a different machine and copy the binary to the cluster?

**Comment by Nirmal2310** [comment]
Ok, I will try that and get back to you. Thank you so much for helping me out.

**Comment by Nirmal2310** [comment]
It worked for me, thank you so much for your help.
